# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "LIS: Legume Information System"
subtitle: Information about legume traits for crop improvement
logo: /assets/img/logo.png
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A collaborative, community resource to facilitate crop improvement by integrating
  genetic, genomic, and trait data across legume species.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: legumefed
github_username: legumeinfo
newsletter: http://eepurl.com/cX_JjL

# Build settings
local_theme: legumeinfo-jekyll-theme
plugins:
  - jekyll-datapage-generator
  - jekyll-feed
  - jekyll-local-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - docker-compose.yml
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

#### jekyll-datapage-generator config

# Manually specifying dir to allow capitalized directory name
#page_gen-dirs: true

page_gen:
  - data: taxa.Arachis.genus_resources.taxon_features
    template: taxon
    dir: taxa/Arachis
# Using "dir: taxa/<genus>" + 'index.html' instead of "page_gen-dirs: true" + "name:" to allow mixed case
#   name: name
    name_expr: "'index'"
    title: name
#   debug: true
  - data: taxa.Cajanus.genus_resources.taxon_features
    template: taxon
    dir: taxa/Cajanus
    name_expr: "'index'"
    title: name
  - data: taxa.Cicer.genus_resources.taxon_features
    template: taxon
    dir: taxa/Cicer
    name_expr: "'index'"
    title: name
  - data: taxa.Glycine.genus_resources.taxon_features
    template: taxon
    dir: taxa/Glycine
    name_expr: "'index'"
    title: name
  - data: taxa.Lens.genus_resources.taxon_features
    template: taxon
    dir: taxa/Lens
    name_expr: "'index'"
    title: name
  - data: taxa.Lotus.genus_resources.taxon_features
    template: taxon
    dir: taxa/Lotus
    name_expr: "'index'"
    title: name
  - data: taxa.Lupinus.genus_resources.taxon_features
    template: taxon
    dir: taxa/Lupinus
    name_expr: "'index'"
    title: name
  - data: taxa.Medicago.genus_resources.taxon_features
    template: taxon
    dir: taxa/Medicago
    name_expr: "'index'"
    title: name
  - data: taxa.Phaseolus.genus_resources.taxon_features
    template: taxon
    dir: taxa/Phaseolus
    name_expr: "'index'"
    title: name
  - data: taxa.Pisum.genus_resources.taxon_features
    template: taxon
    dir: taxa/Pisum
    name_expr: "'index'"
    title: name
  - data: taxa.Trifolium.genus_resources.taxon_features
    template: taxon
    dir: taxa/Trifolium
    name_expr: "'index'"
    title: name
