services:
  jekyll:
    image: jekyll/jekyll:4.2.0
    volumes:
      - ./:/srv/jekyll
      - bundle-cache:/usr/local/bundle
      - gem-cache:/usr/gem
## for Windows hosts
    environment:
      VERBOSE: 1
#     FORCE_POLLING: 1
    command: jekyll serve --incremental --livereload
    ports:
      - "4000:4000"
      - "35729:35729"

volumes:
  bundle-cache:
  gem-cache:
